### ISSUE TITLE
Error: symbol not found

### ISSUE THREAD

**Issue by maesben** [mpco/Alfred3-workflow-recent-documents#19]
I debuged the workflow, since I did not get any results. This is the debug output for RD and RA. If needed, I can provide more outputs. I have an M1 Macbook Pro with the latest update (Big Sur 11.2.3)

RF---
[09:29:35.551] Logging Started...
[09:29:44.123] Recent Documents / Apps[Hotkey] Processing complete
[09:29:44.128] Recent Documents / Apps[Hotkey] Passing output '' to Script Filter
[09:29:44.159] Recent Documents / Apps[Script Filter] Queuing argument '(null)'
[09:29:44.364] Recent Documents / Apps[Script Filter] Script with argv '(null)' finished
[09:29:44.364] ERROR: Recent Documents / Apps[Script Filter] Code 1: Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from mac_alias import Bookmark
  File "/Users/USERNAME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A398023-0EED-42B9-A886-F1A6B28EED56/mac_alias/__init__.py", line 1, in <module>
    from .alias import *
  File "/Users/USERNAME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A398023-0EED-42B9-A886-F1A6B28EED56/mac_alias/alias.py", line 15, in <module>
    from . import osx
  File "/Users/USERNAME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A398023-0EED-42B9-A886-F1A6B28EED56/mac_alias/osx.py", line 424, in <module>
    _statfs = libc['statfs$INODE64']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x1011e9690, statfs$INODE64): symbol not found

--- RA:
[09:32:00.183] Logging Stopped.
[09:32:05.060] Logging Started...
[09:32:09.742] Recent Documents / Apps[Script Filter] Queuing argument '(null)'
[09:32:09.948] Recent Documents / Apps[Script Filter] Script with argv '(null)' finished
[09:32:09.956] ERROR: Recent Documents / Apps[Script Filter] Code 1: Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from mac_alias import Bookmark
  File "/Users/USERNAME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A398023-0EED-42B9-A886-F1A6B28EED56/mac_alias/__init__.py", line 1, in <module>
    from .alias import *
  File "/Users/USERNAME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A398023-0EED-42B9-A886-F1A6B28EED56/mac_alias/alias.py", line 15, in <module>
    from . import osx
  File "/Users/USERNAME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A398023-0EED-42B9-A886-F1A6B28EED56/mac_alias/osx.py", line 424, in <module>
    _statfs = libc['statfs$INODE64']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x104589690, statfs$INODE64): symbol not found

**Comment by xillllite** [comment]
I have the same problem. I solve it by replacing mac_alias with the latest version. And it works.

**Comment by maesben** [comment]
> I have the same problem. I solve it by replacing mac_alias with the latest version. And it works.

This indeed is the solution. Since I had to do some searching, for future references, I downloaded the lates mac-alias package from here: https://pypi.org/project/mac-alias/#files and replaced the files in /Users/USERNAME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.STRING/mac_alias/ with the files in the package. Now, this workflow works!

**Comment by Blackvz** [comment]
> > I have the same problem. I solve it by replacing mac_alias with the latest version. And it works.
> 
> This indeed is the solution. Since I had to do some searching, for future references, I downloaded the lates mac-alias package from here: https://pypi.org/project/mac-alias/#files and replaced the files in /Users/USERNAME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.STRING/mac_alias/ with the files in the package. Now, this workflow works!

Did the same. Now I get another error:
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/12122294/113416644-0d3d6d00-93c2-11eb-9eb2-8c52faa9179a.png">

**Comment by philipbo** [comment]
> > > I have the same problem. I solve it by replacing mac_alias with the latest version. And it works.
> > 
> > 
> > This indeed is the solution. Since I had to do some searching, for future references, I downloaded the lates mac-alias package from here: https://pypi.org/project/mac-alias/#files and replaced the files in /Users/USERNAME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.STRING/mac_alias/ with the files in the package. Now, this workflow works!
> 
> Did the same. Now I get another error: <img alt="image" width="1100" src="https://user-images.githubusercontent.com/12122294/113416644-0d3d6d00-93c2-11eb-9eb2-8c52faa9179a.png">

Allowing Full Disk Access gives Alfred access to the user-level files on your Disk。
